[2025-03-05T09:12:45.342+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-05T09:12:45.378+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ml_pipeline_demo.getmetrics manual__2025-03-05T09:12:24.332456+00:00 [queued]>
[2025-03-05T09:12:45.393+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ml_pipeline_demo.getmetrics manual__2025-03-05T09:12:24.332456+00:00 [queued]>
[2025-03-05T09:12:45.394+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 1
[2025-03-05T09:12:45.416+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): getmetrics> on 2025-03-05 09:12:24.332456+00:00
[2025-03-05T09:12:45.432+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=878) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-03-05T09:12:45.436+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'ml_pipeline_demo', 'getmetrics', 'manual__2025-03-05T09:12:24.332456+00:00', '--job-id', '38', '--raw', '--subdir', 'DAGS_FOLDER/ml_pipeline.py', '--cfg-path', '/tmp/tmpejcchn8f']
[2025-03-05T09:12:45.439+0000] {standard_task_runner.py:105} INFO - Job 38: Subtask getmetrics
[2025-03-05T09:12:45.439+0000] {standard_task_runner.py:72} INFO - Started process 891 to run task
[2025-03-05T09:12:45.576+0000] {task_command.py:467} INFO - Running <TaskInstance: ml_pipeline_demo.getmetrics manual__2025-03-05T09:12:24.332456+00:00 [running]> on host aacdd75e5d47
[2025-03-05T09:12:45.778+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='ml_pipeline_demo' AIRFLOW_CTX_TASK_ID='getmetrics' AIRFLOW_CTX_EXECUTION_DATE='2025-03-05T09:12:24.332456+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-05T09:12:24.332456+00:00'
[2025-03-05T09:12:45.783+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-03-05T09:12:45.784+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-03-05T09:12:45.785+0000] {logging_mixin.py:190} INFO - Current task name:getmetrics state:running start_date:2025-03-05 09:12:45.379744+00:00
[2025-03-05T09:12:45.786+0000] {logging_mixin.py:190} INFO - Dag name:ml_pipeline_demo and current dag run status:running
[2025-03-05T09:12:45.787+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-05T09:12:45.797+0000] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/ml_pipeline.py", line 75, in get_metrics
    accu = accuracy_score(ytest, y_pred, average='micro')
                          ^^^^^
NameError: name 'ytest' is not defined. Did you mean: 'y_test'?
[2025-03-05T09:12:45.842+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-03-05T09:12:45.843+0000] {logging_mixin.py:190} INFO - Task start:2025-03-05 09:12:45.379744+00:00 end:2025-03-05 09:12:45.841646+00:00 duration:0.461902
[2025-03-05T09:12:45.845+0000] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): getmetrics> dag:<DAG: ml_pipeline_demo> dagrun:<DagRun ml_pipeline_demo @ 2025-03-05 09:12:24.332456+00:00: manual__2025-03-05T09:12:24.332456+00:00, state:running, queued_at: 2025-03-05 09:12:24.383110+00:00. externally triggered: True>
[2025-03-05T09:12:45.846+0000] {logging_mixin.py:190} INFO - Failure caused by name 'ytest' is not defined
[2025-03-05T09:12:45.847+0000] {taskinstance.py:1226} INFO - Marking task as FAILED. dag_id=ml_pipeline_demo, task_id=getmetrics, run_id=manual__2025-03-05T09:12:24.332456+00:00, execution_date=20250305T091224, start_date=20250305T091245, end_date=20250305T091245
[2025-03-05T09:12:45.912+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-05T09:12:45.913+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 38 for task getmetrics (name 'ytest' is not defined; 891)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/ml_pipeline.py", line 75, in get_metrics
    accu = accuracy_score(ytest, y_pred, average='micro')
                          ^^^^^
NameError: name 'ytest' is not defined. Did you mean: 'y_test'?
[2025-03-05T09:12:45.949+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-03-05T09:12:45.983+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-05T09:12:45.987+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
