[2025-03-05T09:03:27.285+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-05T09:03:27.307+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ml_pipeline_demo.training_basic_classifier manual__2025-03-05T09:03:18.141208+00:00 [queued]>
[2025-03-05T09:03:27.318+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ml_pipeline_demo.training_basic_classifier manual__2025-03-05T09:03:18.141208+00:00 [queued]>
[2025-03-05T09:03:27.319+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 1
[2025-03-05T09:03:27.333+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): training_basic_classifier> on 2025-03-05 09:03:18.141208+00:00
[2025-03-05T09:03:27.343+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=333) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-03-05T09:03:27.345+0000] {standard_task_runner.py:72} INFO - Started process 346 to run task
[2025-03-05T09:03:27.344+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'ml_pipeline_demo', 'training_basic_classifier', 'manual__2025-03-05T09:03:18.141208+00:00', '--job-id', '14', '--raw', '--subdir', 'DAGS_FOLDER/ml_pipeline.py', '--cfg-path', '/tmp/tmpq2jf1ovx']
[2025-03-05T09:03:27.346+0000] {standard_task_runner.py:105} INFO - Job 14: Subtask training_basic_classifier
[2025-03-05T09:03:27.392+0000] {task_command.py:467} INFO - Running <TaskInstance: ml_pipeline_demo.training_basic_classifier manual__2025-03-05T09:03:18.141208+00:00 [running]> on host aacdd75e5d47
[2025-03-05T09:03:27.467+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='ml_pipeline_demo' AIRFLOW_CTX_TASK_ID='training_basic_classifier' AIRFLOW_CTX_EXECUTION_DATE='2025-03-05T09:03:18.141208+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-05T09:03:18.141208+00:00'
[2025-03-05T09:03:27.469+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-03-05T09:03:27.470+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-03-05T09:03:27.471+0000] {logging_mixin.py:190} INFO - Current task name:training_basic_classifier state:running start_date:2025-03-05 09:03:27.308421+00:00
[2025-03-05T09:03:27.471+0000] {logging_mixin.py:190} INFO - Dag name:ml_pipeline_demo and current dag run status:running
[2025-03-05T09:03:27.472+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-05T09:03:27.478+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/sklearn/utils/validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

[2025-03-05T09:03:27.626+0000] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/ml_pipeline.py", line 43, in trainbasic_classifier
    with open(f'mlmodel.pkl', wb) as f:
                              ^^
NameError: name 'wb' is not defined
[2025-03-05T09:03:27.649+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-03-05T09:03:27.650+0000] {logging_mixin.py:190} INFO - Task start:2025-03-05 09:03:27.308421+00:00 end:2025-03-05 09:03:27.648620+00:00 duration:0.340199
[2025-03-05T09:03:27.652+0000] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): training_basic_classifier> dag:<DAG: ml_pipeline_demo> dagrun:<DagRun ml_pipeline_demo @ 2025-03-05 09:03:18.141208+00:00: manual__2025-03-05T09:03:18.141208+00:00, state:running, queued_at: 2025-03-05 09:03:18.169217+00:00. externally triggered: True>
[2025-03-05T09:03:27.653+0000] {logging_mixin.py:190} INFO - Failure caused by name 'wb' is not defined
[2025-03-05T09:03:27.654+0000] {taskinstance.py:1226} INFO - Marking task as FAILED. dag_id=ml_pipeline_demo, task_id=training_basic_classifier, run_id=manual__2025-03-05T09:03:18.141208+00:00, execution_date=20250305T090318, start_date=20250305T090327, end_date=20250305T090327
[2025-03-05T09:03:27.709+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-05T09:03:27.710+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 14 for task training_basic_classifier (name 'wb' is not defined; 346)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/ml_pipeline.py", line 43, in trainbasic_classifier
    with open(f'mlmodel.pkl', wb) as f:
                              ^^
NameError: name 'wb' is not defined
[2025-03-05T09:03:27.761+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-03-05T09:03:27.782+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-05T09:03:27.786+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
